Utopia7017/utopia

- lib/view/common_ui/article_detail_textfield.dart
- lib/view/screens/NewArticleScreen/components/article_detail_dialog.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
> article detailed dialog box bug fixed #30

- lib/view/screens/MyArticlesScreen/my_articles_screen.dart
- lib/view/screens/ProfileScreen/components/profile_options.dart
#33  Tabbar implemented in MyArticle Screen with Two Categories 'Published' and "Drafts"
> With refrence to #33 

- lib/utils/helper_widgets.dart
- lib/view/common_ui/article_box.dart
- lib/view/screens/CommentScreen/comment_screen.dart
- lib/view/screens/DisplayArticleScreen/components/floating_button_for_article_options.dart
> Comments updated to database

- lib/view/common_ui/comment_container.dart
- lib/view/screens/CommentScreen/comment_screen.dart
- lib/view/screens/CommentScreen/components/list_comments.dart
In context to #42 this PR implements new feature to add comments on articles.
> users can add comment to articles

- lib/view/common_ui/article_box.dart
- lib/view/common_ui/skeleton.dart
- lib/view/screens/ExploreScreen/components/articles_list.dart
- lib/view/screens/ExploreScreen/explore_screen.dart
- lib/view/screens/Skeletons/article_box_skeleton.dart
- lib/view/shimmers/article_shimmer.dart
- pubspec.lock
- pubspec.yaml
This PR implements one of the tasks from #58
> Shimmer effect for articles

- lib/view/screens/DisplayArticleScreen/display_article_screen.dart
> bug fixed  #68 user can navigate own profile and follow thmselves

- lib/view/screens/DisplayArticleScreen/display_article_screen.dart
PopupmenuButton Added in Display Article Screen
> Pop up menu button added in display article

- lib/view/screens/SearchScreen/search_screen.dart
bug fixed #90 : users should be able to navigate to own profile .
> bug fixed : users shouldn't navigate to own profile#90

- lib/view/common_ui/display_full_image.dart
- pubspec.lock
- pubspec.yaml
Added Zooming feature in article images #106
> zoom-in zoom-out article images #106

- lib/view/common_ui/display_full_image.dart
> bug fixed : images are getting infinitely zoomed #115

- lib/view/screens/CommentScreen/components/list_comments.dart
- lib/view/screens/Skeletons/comment_box_skeleton.dart
- lib/view/shimmers/comment_shimmer.dart
completes one of the tasks from #58
> added shimmer effect for comment box

- lib/services/firebase/notification_service.dart
- lib/view/screens/NotificationScreen/notification_screen.dart
This PR introduces the feature requested by #123
> delete all notification at once and mark all read

- lib/controller/articles_controller.dart
- lib/controller/user_controller.dart
- lib/models/user_model.dart
- lib/view/screens/AuthScreen/signup_screen.dart
- lib/view/screens/UserProfileScreen/user_profile_screen.dart
> Users can now block each other

- lib/controller/my_articles_controller.dart
- lib/enums/enums.dart
- lib/utils/article_body_component.dart
- lib/view/common_ui/draft_article_box.dart
- lib/view/screens/EditDraftScreen/edit_draft_screen.dart
- lib/view/screens/MyArticlesScreen/my_articles_screen.dart
- lib/view/screens/NewArticleScreen/components/save_draft_dialog.dart
- lib/view/screens/NewArticleScreen/new_article_screen.dart
- pubspec.lock
- pubspec.yaml
> resolved #163

- lib/controller/my_articles_controller.dart
- lib/view/screens/NewArticleScreen/components/article_detail_dialog.dart
> article text and title trimmed before publish #166

- lib/view/screens/ProfileScreen/components/top_articles_list.dart
- lib/view/screens/ProfileScreen/profile_screen.dart
- lib/view/screens/Skeletons/rec_article_skeleton.dart
- lib/view/shimmers/rec_article_shimmer.dart
recent article box with shimmer effect #58
> implemented recent article box with shimmer effect #58

- lib/controller/my_articles_controller.dart
> No hot restart required after publish article #154

- lib/view/screens/AuthScreen/signup_screen.dart
- lib/view/screens/ProfileScreen/components/profile_box.dart
> Popupmenu added in profile screen #187

- lib/view/screens/AuthScreen/signup_screen.dart
- lib/view/screens/CommentScreen/comment_screen.dart
- lib/view/screens/CommentScreen/reply_comment_screen.dart
- lib/view/screens/DisplayArticleScreen/components/report_modal_sheet.dart
- lib/view/screens/DisplayArticleScreen/display_article_screen.dart
- lib/view/screens/NotificationScreen/components/box_for_like_notif.dart
- pubspec.lock
- pubspec.yaml
> select specific reason before reporting any article

- android/app/build.gradle
- lib/view/screens/SplashScreen/splash_screen.dart
- pubspec.yaml
> #236 implemented in app update

- lib/view/screens/DisplayArticleScreen/display_article_screen.dart
- pubspec.yaml
> #239 updated image display package to easy image viewer
